import { useState } from "react";
import { FormField } from "../components/freightComponents";
import { emptyFinancialInvoiceForm, emptyFinancialPaymentForm, getLocalTodayDateKey } from "../data/defaults";
import { generateInvoicePdf, generateProfitReportPdf } from "../services/pdf";
import { getNextFinancialInvoiceNumber, getShipmentFinancialLedger, money, paymentAmountUsd } from "../utils/freight";

const expenseCategories = ["Demurage", "Bill of Lading", "Storage", "Port Charges", "Lashing"];
const saleCategories = ["Freight Sale", ...expenseCategories, "Other Income"];
const purchaseCategories = ["Ocean Freight", "Local Transport", "Expense", ...expenseCategories, "Other"];

function newInvoiceForm(activeFxRate) {
  return { ...emptyFinancialInvoiceForm, invoiceDate: getLocalTodayDateKey(), fxRate: String(activeFxRate) };
}

function newPaymentForm(activeFxRate) {
  return { ...emptyFinancialPaymentForm, paidDate: getLocalTodayDateKey(), fxRate: String(activeFxRate) };
}

function amountInCurrency(amountUsd, currency, fxRate) {
  const amount = Number(amountUsd || 0);
  if (currency !== "USD") return amount * (Number(fxRate || 1) || 1);
  return amount;
}

function InvoiceTable({ title, rows, canManagePayments, onEdit, onDelete }) {
  return (
    <div className="financeLedger">
      <h3>{title}</h3>
      <div className="tableWrap">
        <table className="compactTable">
          <thead>
            <tr>
              <th>Invoice</th>
              <th>Date</th>
              <th>Party</th>
              <th>Category</th>
              <th>Tax</th>
              <th>Total USD</th>
              <th>Paid USD</th>
              <th>Balance USD</th>
              <th>Status</th>
              {canManagePayments && <th>Action</th>}
            </tr>
          </thead>
          <tbody>
            {rows.map((row) => (
              <tr key={row.id}>
                <td>
                  <b>{row.invoiceNo || "Not set"}</b>
                  {row.autoGenerated && <small className="systemTag">Calculated</small>}
                </td>
                <td>{row.invoiceDate || "Not set"}</td>
                <td>{row.party || "Not set"}</td>
                <td>{row.category}</td>
                <td>{Number(row.taxRate || 0)}%</td>
                <td>{money(row.totalUsd)}</td>
                <td>{money(row.paidUsd)}</td>
                <td>{money(row.remainingUsd)}</td>
                <td><span className={`ledgerStatus ${row.status.replaceAll(" ", "").toLowerCase()}`}>{row.status}</span></td>
                {canManagePayments && (
                  <td>
                    <div className="actions">
                      <button className="ghostBtn" type="button" onClick={() => onEdit(row)}>Edit</button>
                      {!row.autoGenerated && (
                        <button className="dangerBtn" type="button" onClick={() => onDelete(row.id)}>Delete</button>
                      )}
                    </div>
                  </td>
                )}
              </tr>
            ))}
            {rows.length === 0 && (
              <tr><td colSpan={canManagePayments ? 10 : 9}>No invoices recorded.</td></tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}

export function FinancialManagementScreen({ shipments, activeFxRate, canManagePayments, saveFinancialInvoice, deleteFinancialInvoice, addInvoicePayment, assignInvoicePayment }) {
  const [selectedShipmentId, setSelectedShipmentId] = useState("");
  const [invoiceForm, setInvoiceForm] = useState(() => newInvoiceForm(activeFxRate));
  const [editingInvoiceId, setEditingInvoiceId] = useState(null);
  const [replacingCalculatedInvoice, setReplacingCalculatedInvoice] = useState(false);
  const [calculatedInvoiceId, setCalculatedInvoiceId] = useState(null);
  const [paymentForm, setPaymentForm] = useState(() => newPaymentForm(activeFxRate));
  const [allocationTargets, setAllocationTargets] = useState({});

  const shipmentId = selectedShipmentId || shipments[0]?.id || "";
  const shipment = shipments.find((item) => item.id === shipmentId);
  const ledger = shipment ? getShipmentFinancialLedger(shipment, activeFxRate) : null;
  const invoiceNumber = editingInvoiceId
    ? invoiceForm.invoiceNo
    : shipment ? getNextFinancialInvoiceNumber(shipment, invoiceForm.invoiceType) : "";

  function updateInvoice(field, value) {
    setInvoiceForm((previous) => {
      if (field !== "invoiceType") return { ...previous, [field]: value };
      return {
        ...previous,
        invoiceType: value,
        category: value === "Sale" ? "Freight Sale" : "Ocean Freight",
      };
    });
  }

  function selectPaymentInvoice(invoiceId) {
    const invoice = ledger?.rows.find((row) => row.id === invoiceId);
    setPaymentForm((previous) => {
      if (!invoice) return { ...previous, invoiceId, amount: "", taxRate: "0" };
      const currency = invoice.currency || previous.currency || "USD";
      const fxRate = String(invoice.fxRate || previous.fxRate || activeFxRate);
      return {
        ...previous,
        invoiceId,
        currency,
        fxRate,
        taxRate: String(invoice.taxRate || 0),
        amount: String(amountInCurrency(invoice.remainingUsd, currency, fxRate).toFixed(2)),
      };
    });
  }

  function updatePaymentCurrency(currency) {
    const invoice = ledger?.rows.find((row) => row.id === paymentForm.invoiceId);
    setPaymentForm((previous) => ({
      ...previous,
      currency,
      amount: invoice ? String(amountInCurrency(invoice.remainingUsd, currency, previous.fxRate || activeFxRate).toFixed(2)) : previous.amount,
    }));
  }

  function submitInvoice(event) {
    event.preventDefault();
    if (!shipment) return;
    if (!invoiceForm.party.trim() || !invoiceForm.amount) {
      alert("Please enter party and amount.");
      return;
    }
    saveFinancialInvoice(shipment.id, invoiceForm, editingInvoiceId, calculatedInvoiceId);
    setEditingInvoiceId(null);
    setReplacingCalculatedInvoice(false);
    setCalculatedInvoiceId(null);
    setInvoiceForm(newInvoiceForm(activeFxRate));
  }

  function startEditInvoice(invoice) {
    setEditingInvoiceId(invoice.autoGenerated ? null : invoice.id);
    setReplacingCalculatedInvoice(Boolean(invoice.autoGenerated));
    setCalculatedInvoiceId(invoice.autoGenerated ? invoice.id : null);
    setInvoiceForm({
      ...newInvoiceForm(activeFxRate),
      ...invoice,
      id: undefined,
      invoiceNo: invoice.autoGenerated ? "" : invoice.invoiceNo,
      autoGenerated: undefined,
      amount: String(invoice.amount || ""),
      taxRate: String(invoice.taxRate || 0),
      fxRate: String(invoice.fxRate || activeFxRate),
    });
  }

  function cancelInvoiceEdit() {
    setEditingInvoiceId(null);
    setReplacingCalculatedInvoice(false);
    setCalculatedInvoiceId(null);
    setInvoiceForm(newInvoiceForm(activeFxRate));
  }

  function submitPayment(event) {
    event.preventDefault();
    if (!shipment || !paymentForm.invoiceId || !paymentForm.amount) {
      alert("Please select invoice and enter amount.");
      return;
    }
    const invoice = ledger.rows.find((row) => row.id === paymentForm.invoiceId);
    if (!invoice) return;
    addInvoicePayment(shipment.id, invoice, paymentForm);
    setPaymentForm(newPaymentForm(activeFxRate));
  }

  function selectShipment(event) {
    setSelectedShipmentId(event.target.value);
    setEditingInvoiceId(null);
    setReplacingCalculatedInvoice(false);
    setCalculatedInvoiceId(null);
    setInvoiceForm(newInvoiceForm(activeFxRate));
    setPaymentForm(newPaymentForm(activeFxRate));
    setAllocationTargets({});
  }

  return (
    <section className="panel financeManagement">
      <div className="panelHead">
        <div>
          <h2>Financial Management</h2>
          <p className="smallText">Invoices, payments, and shipment profitability in one financial file.</p>
        </div>
        {shipment && (
          <div className="actions">
            <button className="ghostBtn" type="button" onClick={() => generateProfitReportPdf(shipment, activeFxRate)}>Profit Report PDF</button>
            <button className="saveBtn" type="button" onClick={() => generateInvoicePdf(shipment, activeFxRate)}>Customer Invoice PDF</button>
          </div>
        )}
      </div>

      <div className="financeShipmentPicker">
        <FormField label="Shipment File">
          <select value={shipmentId} onChange={selectShipment}>
            {shipments.map((item) => (
              <option key={item.id} value={item.id}>{item.id} - {item.customer} - {item.bookingNo || "Not set"}</option>
            ))}
          </select>
        </FormField>
      </div>

      {!shipment && <div className="note"><p>No shipments available.</p></div>}

      {shipment && ledger && (
        <>
          <div className="financeFileHead">
            <div>
              <h3>{shipment.id} - {shipment.customer}</h3>
              <p>{shipment.pol} to {shipment.pod} | Booking: {shipment.bookingNo || "Not set"} | Entry: {shipment.entryDate || "Not set"}</p>
            </div>
            <span className="badge">{shipment.status}</span>
          </div>

          <div className="financeMetrics">
            <div className="financeMetric"><small>Sales Invoices</small><b>{money(ledger.salesTotal)}</b><span>Remaining {money(ledger.salesRemaining)}</span></div>
            <div className="financeMetric"><small>Purchase Invoices</small><b>{money(ledger.purchasesTotal)}</b><span>Remaining {money(ledger.purchasesRemaining)}</span></div>
            <div className="financeMetric profit"><small>Expected Profit</small><b>{money(ledger.expectedProfit)}</b><span>Sales minus purchases</span></div>
            <div className="financeMetric cash"><small>Cash Position</small><b>{money(ledger.cashPosition)}</b><span>In {money(ledger.cashIn)} / Out {money(ledger.cashOut)}</span></div>
          </div>

          <InvoiceTable title="Sales Invoices" rows={ledger.saleRows} canManagePayments={canManagePayments} onEdit={startEditInvoice} onDelete={(id) => deleteFinancialInvoice(shipment.id, id)} />
          <InvoiceTable title="Purchase Invoices" rows={ledger.purchaseRows} canManagePayments={canManagePayments} onEdit={startEditInvoice} onDelete={(id) => deleteFinancialInvoice(shipment.id, id)} />

          {ledger.unallocatedPayments.length > 0 && (
            <div className="financeLedger">
              <h3>Unallocated Payments</h3>
              <div className="miniList">
                {ledger.unallocatedPayments.map((payment) => (
                  <div className="transportLine" key={payment.id}>
                    <span>{payment.paidDate || "No date"} - {payment.purchaseType} - {payment.company || "Not set"}</span>
                    <b>{money(paymentAmountUsd(payment, shipment, activeFxRate))}</b>
                    {canManagePayments && (
                      <div className="allocationActions">
                        <select value={allocationTargets[payment.id] || ""} onChange={(event) => setAllocationTargets((previous) => ({ ...previous, [payment.id]: event.target.value }))}>
                          <option value="">Select Invoice</option>
                          {ledger.rows.map((row) => <option key={row.id} value={row.id}>{row.invoiceNo} - {row.category}</option>)}
                        </select>
                        <button className="ghostBtn" type="button" disabled={!allocationTargets[payment.id]} onClick={() => assignInvoicePayment(shipment.id, payment.id, allocationTargets[payment.id])}>Allocate</button>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {canManagePayments && (
            <div className="financeForms">
              <form className="financeForm" onSubmit={submitInvoice}>
                <h3>{editingInvoiceId || replacingCalculatedInvoice ? "Edit Invoice" : "Add Invoice"}</h3>
                {replacingCalculatedInvoice && <p className="smallText">Saving replaces the calculated entry with a recorded invoice and assigns its automatic invoice number.</p>}
                <div className="formGrid">
                  <FormField label="Invoice Type"><select value={invoiceForm.invoiceType} onChange={(event) => updateInvoice("invoiceType", event.target.value)} disabled={Boolean(editingInvoiceId) || replacingCalculatedInvoice}><option value="Sale">Sale</option><option value="Purchase">Purchase</option></select></FormField>
                  <FormField label="Category">
                    <select value={invoiceForm.category} onChange={(event) => updateInvoice("category", event.target.value)} disabled={Boolean(editingInvoiceId) || replacingCalculatedInvoice}>
                      {invoiceForm.invoiceType === "Sale" ? (
                        saleCategories.map((category) => <option key={category} value={category}>{category}</option>)
                      ) : (
                        purchaseCategories.map((category) => <option key={category} value={category}>{category}</option>)
                      )}
                    </select>
                  </FormField>
                  <FormField label="Invoice Number"><input value={invoiceNumber} readOnly /></FormField>
                  <FormField label="Invoice Date"><input type="date" value={invoiceForm.invoiceDate} onChange={(event) => updateInvoice("invoiceDate", event.target.value)} /></FormField>
                  <FormField label="Due Date"><input type="date" value={invoiceForm.dueDate} onChange={(event) => updateInvoice("dueDate", event.target.value)} /></FormField>
                  <FormField label="Customer / Supplier"><input value={invoiceForm.party} onChange={(event) => updateInvoice("party", event.target.value)} /></FormField>
                  <FormField label="Amount Before Tax"><input type="number" step="0.01" value={invoiceForm.amount} onChange={(event) => updateInvoice("amount", event.target.value)} /></FormField>
                  <FormField label="Tax Rate %"><input type="number" step="0.01" value={invoiceForm.taxRate} onChange={(event) => updateInvoice("taxRate", event.target.value)} /></FormField>
                  <FormField label="Currency"><select value={invoiceForm.currency} onChange={(event) => updateInvoice("currency", event.target.value)}><option value="USD">USD</option><option value="TRY">TRY</option><option value="EUR">EUR</option></select></FormField>
                  <FormField label="FX Rate to USD"><input type="number" step="0.0001" value={invoiceForm.fxRate} onChange={(event) => updateInvoice("fxRate", event.target.value)} /></FormField>
                  <FormField label="Note"><input value={invoiceForm.note} onChange={(event) => updateInvoice("note", event.target.value)} /></FormField>
                </div>
                <div className="actions mt">
                  <button className="saveBtn" type="submit">{editingInvoiceId || replacingCalculatedInvoice ? "Save Invoice" : "Add Invoice"}</button>
                  {(editingInvoiceId || replacingCalculatedInvoice) && <button className="ghostBtn" type="button" onClick={cancelInvoiceEdit}>Cancel</button>}
                </div>
              </form>

              <form className="financeForm" onSubmit={submitPayment}>
                <h3>Record Invoice Payment</h3>
                <div className="formGrid">
                  <FormField label="Invoice">
                    <select value={paymentForm.invoiceId} onChange={(event) => selectPaymentInvoice(event.target.value)}>
                      <option value="">Select Invoice</option>
                      {ledger.rows.map((row) => <option key={row.id} value={row.id}>{row.invoiceNo} - {row.invoiceType} - {money(row.remainingUsd)}</option>)}
                    </select>
                  </FormField>
                  <FormField label="Amount"><input type="number" step="0.01" value={paymentForm.amount} onChange={(event) => setPaymentForm((previous) => ({ ...previous, amount: event.target.value }))} /></FormField>
                  <FormField label="Tax Rate %"><input type="number" step="0.01" value={paymentForm.taxRate} onChange={(event) => setPaymentForm((previous) => ({ ...previous, taxRate: event.target.value }))} /></FormField>
                  <FormField label="Currency"><select value={paymentForm.currency} onChange={(event) => updatePaymentCurrency(event.target.value)}><option value="USD">USD</option><option value="TRY">TRY</option><option value="EUR">EUR</option></select></FormField>
                  <FormField label="FX Rate to USD"><input type="number" step="0.0001" value={paymentForm.fxRate} onChange={(event) => setPaymentForm((previous) => ({ ...previous, fxRate: event.target.value }))} /></FormField>
                  <FormField label="Payment Date"><input type="date" value={paymentForm.paidDate} onChange={(event) => setPaymentForm((previous) => ({ ...previous, paidDate: event.target.value }))} /></FormField>
                  <FormField label="Note"><input value={paymentForm.note} onChange={(event) => setPaymentForm((previous) => ({ ...previous, note: event.target.value }))} /></FormField>
                </div>
                <button className="saveBtn mt" type="submit">Record Payment</button>
              </form>
            </div>
          )}
        </>
      )}
    </section>
  );
}
